### ISSUE TITLE
Installation on Mint and other Linuxes using sudo

### ISSUE THREAD

**Issue by mkorban** [tshemsedinov/impress#196]
Добрый день.
При попытке установить impress (на только установленный сервер Ubuntu 14.04) получаю сообщение об ошибке:
```
root@app:/impress# npm install impress

> impress@0.1.195 install /impress/node_modules/impress
> node install.js

Installing Impress Application Server...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EACCES, open '/impress/server.js'
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "impress"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! impress@0.1.195 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the impress@0.1.195 install script 'node install.js'.
npm ERR! This is most likely a problem with the impress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls impress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /impress/npm-debug.log

root@app:/impress#

**Comment by tshemsedinov** [comment]
Он установился, но не смог запуститься, потому, что не хватает прав сесть на 80 порт, попробуйте зайти под рутом и запустить из консоли ```node server.js``` или выдайте права или нужно переконфигурировать на другой порт в /config/servers.js, берите любой порт больше 1024, на него права должны быть.

**Comment by mkorban** [comment]
Я запускал от рута, и в папке /impress/node_modules не появился impress
```
root@app:/impress# cd /impress
root@app:/impress# ls -a
.  ..  node_modules  npm-debug.log
root@app:/impress# ls -la
total 460
drwxr-xr-x  3 root   root     4096 Jan 12 15:59 .
drwxr-xr-x 23 root   root     4096 Jan 12 14:16 ..
drwxr-xr-x  7 korban korban   4096 Jan 12 15:59 node_modules
-rw-r--r--  1 root   root   456466 Jan 12 15:59 npm-debug.log
root@app:/impress#

**Comment by mkorban** [comment]
В лог-файле npm-debug.log есть следующая запись:
```
3449 info install impress@0.1.195
3450 verbose unsafe-perm in lifecycle false
3451 info impress@0.1.195 Failed to exec install script
3452 verbose unlock done using /home/korban/.npm/_locks/impress-f14398170820f02b.lock for /impress/node_modules/impress
3453 verbose stack Error: impress@0.1.195 install: `node install.js`
3453 verbose stack Exit status 8
3453 verbose stack     at EventEmitter.<anonymous>  (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
3453 verbose stack     at EventEmitter.emit (events.js:98:17)
3453 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
3453 verbose stack     at ChildProcess.emit (events.js:98:17)
3453 verbose stack     at maybeClose (child_process.js:766:16)
3453 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by tshemsedinov** [comment]
А если sudo ```npm install impress```

**Comment by mkorban** [comment]
Нет, не помогло.
Установился и запустился только после того, как я дал права 
777 на /impress и на /impress/node_modules

**Comment by mkorban** [comment]
Вот что получилось. Возможно эта информация пригодится:
Система: Linux Mint 17 64-bit
impress устанавливается и запускается корректно только при условии, что запуск **npm install impress** происходит именно от root. Если войти в систему от имени обычного пользователя, а потом сделать **sudo npm install impress** или даже **sudo bash** и потом уже **npm install impress** - то установка заканчивается ошибкой, а именно, impress не устанавливается как сервис и не может запустится. При этом в процессах видно, что несмотря на sudo процесс **node install.js** запускается от имени пользователя, который делал sudo.

**Comment by tshemsedinov** [comment]
Спасибо! Со временем протестируем на разных линуксах, пока тестирование проходит для CentOS, Ubuntu, Debian. Вообще под root или через sudo всегда работало.

**Comment by tshemsedinov** [comment]
Tested on CentOS, Debian, Ubuntu, Mint, works well. Install and start Impress using root account.
