### ISSUE TITLE
Самое начало...

### ISSUE THREAD

**Issue by vlastv** [tshemsedinov/impress#197]
Правильно ли я понял, что для получения, например, списка пользователей в json и csv мне необходимо один и тот же код (получения пользователей из БД) дублировать в двух файлах в папках method.json и method.csv ? 

Есть ли пример, реализации сборки различных методов в один для возврата html страницы без дублирование кода. В такой ситуации:
есть методы API получения информации о пользователе ```/api/about``` и получении новостей ```/api/news```. Данные методы, допустим, используются в нативных приложения.
А есть "веб-морда", например, ```/home``` где надо отобразить информацию возвращаемую двумя методами API приведенными выше.

**Comment by tshemsedinov** [comment]
Добавил пример, как лучше это делать:
1. Слой внутреннего API для всего приложения можно положить в ```/lib```, вот так ```/applications/example/lib/internalApi.js```
2. Теперь обращаемся к API из группы примеров: ```/applications/example/app/examples/news```
2.1. Выводим в таблицу в случайном порядке ```GET /examples/news/randomList.ajax```, обработчик - ```get.js```, шаблон - ```html.template```
2.2. Выводим один элемент, каждый раз берем следующий, по завершению массива начинаем брать с самого начала ```GET /examples/news/next.json/```
2.3. Выводим заголовки новостей ```GET /examples/news/titles.json/```
2.4. Теперь еще один фокус, один обработчик на два формата данных:
/applications/example/app/examples/news/item/request.js
2.4.1. Получаем ответ в JSON ```GET /examples/news/item/asObject.json?id=2```
2.4.2. Получаем ответ в HTML ```GET /examples/news/item/asHtml.ajax?id=2```

**Comment by tshemsedinov** [comment]
Тут вся штука в том, что не нужно смешивать сетевое API, Доступное из клиента и API внутри серверного приложения. Это два разные слоя логики, сетевое API базируется на внутреннем API сервера. В новую версию 0.1.196 (что уже в npm) вошли примеры, можно поставить и посмотреть код. Объем кода для внутреннего API - 1617 байт, а для 5 методов сетевого API - 877 байт.
