### ISSUE TITLE
Add minimal application skeleton

### ISSUE THREAD

**Issue by kolonist** [tshemsedinov/impress#208]
Need minimal application skeleton, without any additional units or something like that.

Trying to create simple GET handler like `http://news39.lo:8080/api/test.json`. Have the following directories:
```bash
applications/
└── news39.lo
    ├── app
    │   └── api
    │       └── test.json
    │           └── get.js
    └── config
        ├── hosts.js
        └── sandbox.js
```

_get.js_ is:
```javascript
module.exports = function(client, callback) {
    callback({
        field1: 'Field 1',
        field2: 'Field 2'
    });
};
```

_hosts.js_ is:
```javascript
module.exports = [
      'news39.lo',
    '*.news39.lo'
];
```

_sandbox.js_ copied from _impress/config_ without any changes.

Get following output:
```bash
$ ./server.sh 
Impress Application Server starting, reading configuration
Warning: plugin impress.log.js is not loaded
Startup check: http://127.0.0.1/
  HTTP listen on 127.0.0.1:8080
2015-01-17T12:26:50.728Z
Master(21512/C1N0)
TypeError: Cannot read property 'staticRx' of undefined
  EventEmitter.application.dispatch (impress.application.js:427:33)
  Server.impress.dispatcher (impress.js:594:75)
  Server.emit (events.js:98:17)
  HTTPParser.parser.onIncoming (http.js:2113:12)
  HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
  Socket.socket.ondata (http.js:1971:22)
  TCP.onread (net.js:528:27)

Impress shutting down
```

**Comment by tshemsedinov** [comment]
Here is minimal example: https://github.com/tshemsedinov/impress/tree/master/examples/minimalApplication
You can clone this directory and install as usual ```npm install```

**Comment by kolonist** [comment]
Thank you, it will be helpful! I will try it soon.

But do I really need all that files and directories for such a simple application? What if mark some directories and files as required and allow to avoid creation of optional ones?

**Comment by tshemsedinov** [comment]
I'll try to minimize required files and directories but 32kb is not very big for minimal application. Impress in not a platform for simple applications and I don't think that I can upgrade it for something like quick start with 3 code lines and run. What will solve the problem is a command line interface to create new empty app from template, e.g.: ```impress new``` ( https://github.com/tshemsedinov/impress/issues/157 )

**Comment by kolonist** [comment]
> What will solve the problem is a command line interface to create new empty app from template, e.g.: impress new

Oh, yea, it's true.
