### ISSUE TITLE
Service on CentOS 7 can't be stopped, no killall

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#209]
```service impress stop``` fails to stop impress

**Comment by johnbizokk** [comment]
Добрый день, Тимур!
В ходе чистой инсталляции npm install impess на CentOS 7, проблема сохраняется.  А фикс  https://github.com/tshemsedinov/impress/commit/7cd8a344692796bae0655479a8d4f291e5302d51
решает проблему только при разворачивании через скрипт https://github.com/tshemsedinov/impress/blob/3da2a6304295406ae2c0b189e30fae34e76db193/deploy/centos7x64.sh. 
Выдаваемая ошибка при чистой установке
***Error: Command failed: /bin/sh -c killall "impress srv"*** 
и 
***/bin/sh: killall: command not found***.
Хотя следует заметить что процесс ***impress srv*** всё таки завершается, потому что при запуске директивы ExecStop в service файле, если не задан корректный способ остановки процесса то systemd -  *gracefully kill the process and any other processes it spawned*. То есть, можно и не указывать способ убийства процесса, а использовать возможности ***ExecStop*** данные по умолчанию. Либо, как вариант, можно в теле stop функции заменить команду killall на kill,
 например, *kill $(ps -e |grep "impress srv" | awk '{print $1;}')*.

**Comment by tshemsedinov** [comment]
Все инсталляции должны быть через скрипт. Если хочешь избавиться от зависимости psmisc т.е. от killall, то делай пул-реквест. Но лучше добавить в установку Impress через npm проверку на psmisc и его установку если нету.
