### ISSUE TITLE
Immediate (live) reload /model

### ISSUE THREAD

**Issue by aagafonov** [tshemsedinov/impress#220]
Timur,  could you please think of a place where one could create global variables that become visible immidiately (not after restart)

**Comment by tshemsedinov** [comment]
Use the global Luke
![3b53ac1e11093b046b26181ebda2cc78](https://cloud.githubusercontent.com/assets/4405297/6010916/469db112-ab3f-11e4-9ecf-3d74de9985ee.jpg)

**Comment by ernado-x** [comment]
:+1:

**Comment by tshemsedinov** [comment]
Все сделаем, будет /model мониториться на предмет изменений, как сейчас /config мониторится, а там уж хоть в глобал пиши, хоть на ушах стой
