### ISSUE TITLE
Loading templates by session usergroup stopped working since at least 0.1.188

### ISSUE THREAD

**Issue by aagafonov** [tshemsedinov/impress#223]
After recent update i've lost functionality which provided the ability to load template using session usergroup by inserting its value like: html.admin.template

**Comment by tshemsedinov** [comment]
This function works, you need to fix templates, add plugins: 'db', 'db.mongodb', 'impress.security.mongodb' in sandbox.js and if problem remains write to me.

**Comment by aagafonov** [comment]
In previous versions i've been using client.application.users[id].group = "admins" - to add a group that maps to template.
But in latest version i have to strip "client" and write application.users["id].group = "admins";
