### ISSUE TITLE
Remove jQuery dependency in client-side code

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#237]

**Comment by tshemsedinov** [comment]
Клиентский код имеет зависимость от jQuery, и там не красиво написан старый кусок кода, связанный с показом диалоговых окон (затемнение экрана и попап)
https://github.com/tshemsedinov/impress/blob/master/examples/exampleApplication/applications/example/static/js/impress.js нужно бы это исправить, как у тебя со временем, @j-martyn ?

**Comment by j-martyn** [comment]
Сегодня-завтра поправлю.

**Comment by tshemsedinov** [comment]
Сначала забери последние правки к себе в ветку.

**Comment by tshemsedinov** [comment]
Реализация попапа без зависимостей
Но нам нужен попап с дополнительными функциями, см ниже
```JavaScript
// Popup implementation with no dependencies
function popUp(html) {
  var back = document.createElement('div'),
      pop = document.createElement('div'),
      msg = document.createElement('div');
  back.className = 'popUpBackground';
  back.style.width = '100%';
  back.style.height = '100%';
  back.style.top = '0px';
  back.style.left = '0px';
  back.style.position = 'absolute';
  back.style.opacity = '.50';
  back.style.opacity = 'alpha(opacity=50)'; // -moz-opacity
  back.style.backgroundColor = '#000';
  pop.className = 'popUpWindow';
  pop.style.position = 'absolute';
  pop.style.backgroundColor = 'white';
  pop.style.padding = '15px';
  pop.style.top = '100px';
  pop.style.left = '100px';
  pop.style.bottom = '100px';
  pop.style.right = '100px';
  pop.style.boxShadow = '0 0 15px #333';
  msg.innerHTML = html;
  pop.appendChild(msg);
  var closebtn = document.createElement('div');
  closebtn.innerHTML = 'close';
  closebtn.onclick = closePopUp;
  back.onclick = closePopUp;
  pop.appendChild(closebtn);
  document.body.appendChild(back);
  document.body.appendChild(pop);
  function closePopUp() {
    document.body.removeChild(pop);
    document.body.removeChild(back);
  }
}

// Usage:
popUp('Hello <b>World</b> ...');
```

Функции:
1. Размер задается контентом в попапе, в примере я для простоты сделал просто отступы от границ, нужно доработать центрирование или взять его из текущей реализации попапа, который сделан как jQuery плагин
2. При изменении размеров окна все перемещается и пересчитывается красиво
3. Весь CSS должен быть кросс-платформенный, например box-shadow, см. как в текущей реализации. Но не должно быть зависимостей от CSS файлов, нужно все через DOM делать, поищи может есть специальные CSS-JS синтаксисы, это хорошая идея, вместо CSS или LESS использовать JS
4. На маленьких экранах, если контент попапа не помещается по ширине и высоте, то показываем все с отступом небольшим (например 8px), как я сделал в примере и даем внутри попапа прокрутку .
5. Все должно быть выдержано в стиле минимализма и код и внешний вид

Когда уже будут результаты, @j-martyn ?

**Comment by j-martyn** [comment]
Как раз возвратился к задаче. На выходных буду вносить изменения в соответствии с новой инфой, в течении недели выдам.

**Comment by tshemsedinov** [comment]
Заодно посмотри, может есть такая библиотека, чтобы стили присваивать в JS не так:
```JavaScript
pop.style.position = 'absolute';
pop.style.backgroundColor = 'white';
pop.style.padding = '15px';
pop.style.top = '100px';
pop.style.left = '100px';
pop.style.bottom = '100px';
pop.style.right = '100px';
pop.style.boxShadow = '0 0 15px #333';
```
а как-то вот так:
```JavaScript
style(pop, {
  position: 'absolute',
  backgroundColor: 'white',
  padding: '15px',
  top: '100px',
  left: '100px',
  bottom: '100px',
  right: '100px',
  boxShadow: '0 0 15px #333',
});
```
Или напиши, это удобно, мне кажется

**Comment by agil** [comment]
это же делается на чистом js  в две строчки
```javascript
var style = {
    position: 'absolute', 
    padding: '15px'
};

for (var prop in style) {
    pop.style[prop] = style[prop];
}
```

**Comment by tshemsedinov** [comment]
Да, но это обернуть в функцию нужно, чтобы каждый раз не писать циклы, и может есть уже реализации, которые из boxShadow сделают 
```
-webkit-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);
box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);
```
или вообще из именования с тире типа "background-сolor" сделают backgroundColor

**Comment by agil** [comment]
есть style.cssText, в который можно присваивать просто строку со стилями. хотя мне этот вариант меньше нравится. в js коде, имхо, лучше использовать js нотацию.

а для второго есть сборщики, типа webpack, которые позволят собирать под разные требования и  поддержку браузеров просто изменением настройки. причем не только для css но и js(es5, es6) и всего остального. и даже разные версия для разработки и production.
но это все важно не для приложений из папки examples, там и jquery подходит и все что угодно.

**Comment by tshemsedinov** [comment]
Да просто jQuery нужно уже нафиг гнать )

**Comment by j-martyn** [comment]
В https://github.com/tshemsedinov/impress/commit/46e16da81a2d2894ce2c15f29a773fd0a3431743 добавил новую реализацию попапа [`impress.popup`](https://github.com/tshemsedinov/impress/blob/46e16da81a2d2894ce2c15f29a773fd0a3431743/applications/example/static/js/impress.js#L839-L892) и применения стилей [`impress.setStyles`](https://github.com/tshemsedinov/impress/blob/46e16da81a2d2894ce2c15f29a773fd0a3431743/applications/example/static/js/impress.js#L782-L833), работает как с обьектом так и со строкой, и добавляет вендорные префиксы, список соответствий взял из [Emmet](https://github.com/emmetio/emmet/blob/1cb7e8101b9885d27f86a5cf13ade3a23b99c5b4/lib/resolver/css.js#L155-L160). 
Удалил то что очевидно не используется. В init.js jQuery вызовы еще не удалил, там в основном используеться манипуляция DOM, .html(), и триггеры click и focus.

**Comment by tshemsedinov** [comment]
Хорошо
* json2.js тоже удаляем
* alignCenter - нужен был для попапа
* скопированный кусок из Emmet мне не очень нравится, мы же не будем его поддерживать в актуальности, можно добавить зависимость из какого-то приличного места?
* диалоги типа message (попап к кнопкой ок), confirmation (попап с кнопками yes/no), input (папап с вводом строки) нам тоже нужны в общую библиотеку.

**Comment by tshemsedinov** [comment]
Если там что-то уже в приличном виде, то жду pull request в течении недели, @j-martyn

**Comment by tshemsedinov** [comment]
@j-martyn я взял твою реализацию popup, но не через пул-реквест, потому, что исходники сильно изменились с того времени и все это смерджить было уже не возможно без хирургического метода. Так что, все остальные зависимости от jQuery я ликвидировал, а твой код нужно несколько порефакторить и декомпозировать большие функции, обсудим это.
