### ISSUE TITLE
Fix compatibility for CentOS 7

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#239]
Change service and autorun scripts.

**Comment by johnbizokk** [comment]
В CentOS 7 системы инициализации **SysV** или **Upstart** были заменены на **Systemd**. Скрипты инициализации в */etc/rc.d/init.d/* были заменены на сервисные юниты в */etc/systemd/system*. Для CentOS 7 предлагаю создать в */etc/systemd/system*, файл **impress.service**, содержащий 
```
[Unit]
Description=Impress Application Server
After=syslog.target

[Service]
ExecStart=/etc/rc.d/init.d/impress start
ExecStop=/etc/rc.d/init.d/impress stop
ExecReload=/etc/rc.d/init.d/impress restart
Type=forking

[Install]
WantedBy=multi-user.target
```
После создания нужно выполнить команду 
```systemctl daemon-reload``` 
для перезагрузки сервисных юнитов. 
Для конфигурации сервисного юнита, Systemd позволяет использовать директивы:
1. ExecStart
2. ExecStop 
3. ExecReload 
Cоответственно для старта,остановки и перезагрузки impress. 
То есть для управления сервисом impress можна использовать команды 
```systemctl start impress ```
вместо
``` service impress start```

```systemctl stop impress ```
вместо
``` service impress stop```

```systemctl restart impress ```
вместо
``` service impress restart```
**Systemd** не позволяет переопределить команды *status* и *update*, в случае команды status предоставляется встроенная сервисная информация **systemd** о сервисе, для update аналогичная возможность отсутствует.
Предлагаю для status/update или только update использование скрипта(*/etc/rc.d/init.d/impress*) с параметрами *status/update*, так как systemd не предоставляет такой возможности.

**Comment by johnbizokk** [comment]
Также для добавления юнита в **автозапуск** необходимо выполнить команду
```systemctl enable impress.service ```

**Comment by tshemsedinov** [comment]
1. А расширение ".service" это общепринятое для сервисов в systemd? Чтобы может ```systemctl enable impress.service``` как-то можно заменить на ```systemctl enable impress``` ?
2. Может не нужно тянуть за собой старый скрипт в ```/etc/rc.d/init.d/``` ? В нем ничего такого особенного нет или его можно держать в папке самого импреса, а не в системной, ведь ее может просто не быть для systemd.
3. Update можно вообще убрать, мы сделаем отдельный CLI (command line interface) для Impress, который будет доступен везде из командной строки и можно будет писать просто ```impress update```, а для создания нового приложения что-то типа ```impress create domain.com``` и в папке /applications из шаблона появится заготовка приложения, кстати, может тогда сделать вообще ```impress start``` и  ```impress stop``` и т.д.

Ну а исправления в крипты ты можешь внести, делай форк, потом у себя поправь и пушай результат.

**Comment by johnbizokk** [comment]
1.".service" для сервисных юнитов не обязательно, можно стартовать и так 
```systemctl enable impress```
2. В конфигурационном файле impress.service, предлагаю использовать скрипт из **/node_modules/impress/bin/impress**
3. Сделал отдельную ветку *systemd-service* с соответствующими изменениями.

**Comment by tshemsedinov** [comment]
Если все готово, то можешь делать pull request: https://github.com/tshemsedinov/impress/compare/ Тут нужно выбирать base:master, compare:твоя-ветка, получится вот таким образом: https://github.com/tshemsedinov/impress/compare/master...systemd-service

**Comment by tshemsedinov** [comment]
После установки из этого скрипта делаю: ```systemctl start impress``` и получаю:  ```Job for impress.service failed. See 'systemctl status impress.service' and 'journalctl -xn' for details.```. Ну делаю тогда ```journalctl -xn``` и получаю:
```
-- Logs begin at Wed 2015-04-01 19:41:17 CEST, end at Wed 2015-04-01 20:02:55 CEST. --
Apr 01 20:02:55 s1 systemd[1]: Starting Impress Application Server...
-- Subject: Unit impress.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit impress.service has begun starting up.
Apr 01 20:02:55 s1 systemd[38282]: Failed at step EXEC spawning /impress/node_modules/impress/bin/impress: No such file or directory
-- Subject: Process /impress/node_modules/impress/bin/impress could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /impress/node_modules/impress/bin/impress could not be executed and failed.
--
-- The error number returned while executing this process is 2.
Apr 01 20:02:55 s1 systemd[1]: impress.service: control process exited, code=exited status=203
Apr 01 20:02:55 s1 systemd[1]: Failed to start Impress Application Server.
-- Subject: Unit impress.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit impress.service has failed.
--
-- The result is failed.
Apr 01 20:02:55 s1 systemd[1]: Unit impress.service entered failed state.
```

**Comment by tshemsedinov** [comment]
Вывод ```systemctl status impress.service```
такой:
```
impress.service - Impress Application Server
   Loaded: loaded (/etc/systemd/system/impress.service; enabled)
   Active: failed (Result: exit-code) since Wed 2015-04-01 20:02:55 CEST; 4min 12s ago
  Process: 38282 ExecStart=/impress/node_modules/impress/bin/impress start (code=exited, status=203/EXEC)

Apr 01 20:02:55 s1 systemd[1]: Starting Impress Application Server...
Apr 01 20:02:55 s1 systemd[1]: impress.service: control process exited, code=exited status=203
Apr 01 20:02:55 s1 systemd[1]: Failed to start Impress Application Server.
Apr 01 20:02:55 s1 systemd[1]: Unit impress.service entered failed state.
```

**Comment by johnbizokk** [comment]
Проблема в том что при выполнении команды 
```npm install impress```
из скрипта развёртывания из npm забирается битый файл который далее используэться

**Comment by tshemsedinov** [comment]
Так что, 0D0A заменить на 0A ?

**Comment by tshemsedinov** [comment]
Ты не меняй, это у меня гит-клиент постоянно при слитии изменений менет 0A на 0D0A опять, не могу с ним справиться, ```.gitattributes``` настроен, а он все равно гадит.

**Comment by johnbizokk** [comment]
Ну проблема была именно из-за этого.

**Comment by tshemsedinov** [comment]
Ну это только я у себя прямо перед публикацией в npm могу исправить иначе гит-клиент все поправит обратно.
