### ISSUE TITLE
Impress does not install on CentOS 6.6

### ISSUE THREAD

**Issue by tylkomat** [tshemsedinov/impress#240]
I followed the `deploy/centos6x64.sh` script. At the point of `npm install impress` I receive the following error, which does not say much.

    3866 verbose stack Error: impress@0.1.232 install: `node install.js`
    3866 verbose stack Exit status 8
    3866 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
    3866 verbose stack     at EventEmitter.emit (events.js:98:17)
    3866 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
    3866 verbose stack     at ChildProcess.emit (events.js:98:17)
    3866 verbose stack     at maybeClose (child_process.js:756:16)
    3866 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
    3867 verbose pkgid impress@0.1.232
    3868 verbose cwd /impress
    3869 error Linux 2.6.32-504.8.1.el6.x86_64
    3870 error argv "node" "/usr/bin/npm" "install" "impress"
    3871 error node v0.10.33
    3872 error npm  v2.6.1
    3873 error code ELIFECYCLE
    3874 error impress@0.1.232 install: `node install.js`
    3874 error Exit status 8
    3875 error Failed at the impress@0.1.232 install script 'node install.js'.
I hope someone can give me a hint.

**Comment by tshemsedinov** [comment]
I can't reproduce this situation in fresh installed from ```CentOS-6.6-x86_64-minimal.iso```.
But you can try to check following possible reasons:
1. Impress should be installed using root account (or using sudo)
2. By default Impress configured to port 80, so port should be free (not used by another application) or you need to change ```/impress/config/servers.js```
3. All ports below 1024 are privileged and can be used with root account

**Comment by tylkomat** [comment]
I see. Propaply the reason is the 2nd, as apache is running on 80. If I want to keep apache, can I do `git pull`, edit `server.js`  and then `npm install`?

**Comment by tshemsedinov** [comment]
You can create folder for Impress, e.g. ```/impress``` (if you want to use it as service and autorun) or ```/home/tylkomat/impress``` (for testing or development), in this folder execute ```npm install impress``` (if you want to create new application or simple install server) or if you have a project that have Impress as a dependency (in package.json) you can clone this (dependent) project and install executing ```npm install```

**Comment by tshemsedinov** [comment]
After installing edit server.js and start ```node server``` (from project folder) or ```service impress start``` from any place (if it is installed as s service).

**Comment by tylkomat** [comment]
Whencd  I do `npm install impress` inside `/impress` then I receive the error mentioned above. Because of this error npm rolls back everything, so I don't have a chance to edit `server.js`.

**Comment by tshemsedinov** [comment]
Port 80 is not needed in installation process, it is needed when you start Impress, so problem is not in port. Try to use ```sudo npm install impress```.

**Comment by tylkomat** [comment]
I was installing as `root` before there it was not working. Now I tried with `sudo` and it worked fine. Thanks. Just a hint, the `server.sh` script is not executable (had to do `chmod +x`) after the installation, and also the service is not recognized

    sudo service impress start
    impress: unrecognized service
