### ISSUE TITLE
impress service should have unix line endings

### ISSUE THREAD

**Issue by tylkomat** [tshemsedinov/impress#241]
I had to convert the service script `/etc/init.d/impress` with dos2unix otherwise it would not run.

**Comment by tshemsedinov** [comment]
How do you install it? Using github or npm? How it can work for me on CentOS, Ubuntu and Debian and don't work for you? I think npm converts line endings in all sources and scripts, but I'll check it.

**Comment by tylkomat** [comment]
I install it, like you have it in the `centos6x64.sh`. I just did the last steps, as I had Node and npm installed already. For mongo I followed the instructions on the mongodb page, which are similar to yours in that bash script. These are the steps I did manually:

    mkdir /impress
    cd /impress
    npm install mongodb
    npm install nodemailer
    npm install websocket
    npm install geoip-lite
    npm install impress
Nothing special.
