### ISSUE TITLE
Carriage Return problem

### ISSUE THREAD

**Issue by johnbizokk** [tshemsedinov/impress#242]
После инсталляции impress скриптом для centos7 ```https://github.com/tshemsedinov/impress/blob/master/deploy/centos7x64.sh```
скрипт управления **impress** в директория 
```/etc/init.d/``` и  ```node_modules/impress/bin/``` 
имеют неправильные отступы типа **CR+LF**
что при выполнении через sh не позволяет скрипту работать, предлагаю изменить формат на **LF**.

**Comment by tshemsedinov** [comment]
Вчера исправлено, но вообще на 6.6 и так работало, не знаю почему. https://github.com/tshemsedinov/impress/issues/241
