### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#253]
Investigate the possibility of TypeScript support

**Comment by tshemsedinov** [comment]
After a deep study of the issue I decided not to integrate TypeScript support into Impress core. But you can use with preprocess/build to generate JS.

**Comment by KnorpelSenf** [comment]
Did you ever reconsider this? It's no longer 2015 and TypeScript is in a very different position now.

**Comment by tshemsedinov** [comment]
@KnorpelSenf no, as of 2023 we consider TypeScript as additional linter, we use pair .d.ts typings + js files like in c++. This approach allow us to run codebase at any time without compilation, separate contracts and code, use codegeneration from schemas (see metaschema library) to create typings from domain model, at the same time we have all advantages of such an additional linting against types.
