### ISSUE TITLE
cant bind the host/port error

### ISSUE THREAD

**Issue by saurabhghewari** [tshemsedinov/impress#278]
Hiii,
     I have installed impress using npm install command. then i followed the steps given in configuration block of git. i changed the hosts.js and server.js according to them. But i used IP address in both files and not the domain name. I am getting the error cant bind host/port when i restart the server. Where am i going wrong? Please help...

I have apache install listening on 80 port. When apache and impress both are running, i get
server status:server is already running. On stopping the apache i get the above error.

Great work done by you guys!!! Really enjoyed on seeing this work. Keep it Up!!!

**Comment by saurabhghewari** [comment]
![binderror](https://cloud.githubusercontent.com/assets/8543803/7451348/6f2e6610-f26d-11e4-8696-2d7bbe57b09d.png)
![onapacheractive](https://cloud.githubusercontent.com/assets/8543803/7451349/6f2f4968-f26d-11e4-8506-54bf4f6fe4ed.png)

Take a look. The first image is when apache server is stopped.
Second one is apache server running.

**Comment by tshemsedinov** [comment]
Try sudo node server. Probably your account have no rights to use ports below 1024.

**Comment by saurabhghewari** [comment]
Yes that worked. How do you came to know this?

**Comment by tshemsedinov** [comment]
Tat Tvam Asi

**Comment by saurabhghewari** [comment]
Oh my god!!! You know vedas?

**Comment by saurabhghewari** [comment]
Aham Bramhasi!!!

**Comment by tshemsedinov** [comment]
أنا الحق
Sufi should know vedas! )
Any other node.js application will fail to bind on ports below 1024.
So you need to use ```su``` or ```sudo```.
But if you install impress as a service it will work using system rights.

**Comment by saurabhghewari** [comment]
Intresting. I am impressed. I have sent you frend request on FB, please add me. Thanks for helping.

**Comment by SkeLLLa** [comment]
@saurabhghewari, by the way in linux you can allow node to bind on ports below 1024 with following command:
```
sudo setcap 'cap_net_bind_service=+ep' /usr/bin/node
```
If your node is stored somewhere else, then replace `/usr/bin/node` with actual path to node executable.

So after executing this command you'll be able to run node on 80 port without sudo.

**Comment by saurabhghewari** [comment]
Yeah. One thing i like to mention here, running node with sudo command may cause system problems. I read in a blog. I will post the link once i found it.

**Comment by SkeLLLa** [comment]
@saurabhghewari you're correct. I've got a such situations in my practice, especially if there are not a lot of RAM on a server. In such situations (in my case it was on Amazon) node can eat up all memory and the system freezes and after reboot it will not event launch. Only restoring from whole system from backup image can help.

**Comment by saurabhghewari** [comment]
Thanks @SkeLLLa!!!
