### ISSUE TITLE
Настройка security

### ISSUE THREAD

**Issue by ReasonX7** [tshemsedinov/impress#281]
Попробовал в своем приложении сделать процедуру аутентификация юзера. При попытке входа impress выдает ошибку: No security database configured or can not connect to db.
MongoDB соединение отображает. 
Следовательно вопрос, как настраивать security? Облазил приложение-пример в Impress, так и не нашел где это делается.

При попытке входа юзера в систему, в приложении-примере Impress получаю такую ошибку:
Security provider not loaded. Как с ним бороться?

**Comment by tshemsedinov** [comment]
Если пишет ```Security provider not loaded``` то скорее всего не установлены дрова монги: ```npm install mongodb```

**Comment by tshemsedinov** [comment]
Еще в конфигурации сервера и в конфигурации приложения нужно раскомментировать в разделе ```plugins``` такие плагины: ```'db', 'db.schema', 'db.mongodb', 'impress.security.mongodb'```

**Comment by ReasonX7** [comment]
Спасибо.
С Security provider not loaded проблема решена. 
А как быть с No security database configured or can not connect to db? В конфигах все подключено.

**Comment by tshemsedinov** [comment]
Мне не видно, как выглядит конфиг, но в ```database.js``` может быть пропущен флаг ```security: true```

**Comment by ReasonX7** [comment]
Флаг стоит. Конфиг:

  plugins: [
    'db',
    'db.schema',
    'db.mongodb',
    //'db.memcached',
    'db.mysql',
    //'db.pgsql',
    'impress.log',
    'impress.security.mongodb',
    //'impress.health',
    //'impress.scale',
    //'api.uglify',
    //'api.sass',
    //'api.mail',
    'impress.events',
    'impress.sse',
    'impress.websocket',
    'impress.rpc',
    //'impress.passport',
    //'impress.state',
  ]
Это в обоих: для сервера и для приложения.

**Comment by tshemsedinov** [comment]
Это конфиг ```sandbox.js```, в ```database.js``` что?

**Comment by ReasonX7** [comment]
```
module.exports = {
    mysql: {
        url: "mysql://testuser:123@localhost:3306/test",
        slowTime: "1s"
    },

    mongodb: {
        url: "mongodb://localhost:27017/impress",
        collections: [ "users" ],
        slowTime: "2s",
        security: true
    }
};
```

**Comment by ReasonX7** [comment]
Для аутентификации используется mongodb, если что.

**Comment by tshemsedinov** [comment]
Нужно коллекции прописать как минимум ```collections: [ 'sessions', 'users', 'groups' ]```

**Comment by ReasonX7** [comment]
Спасибо!

**Comment by tshemsedinov** [comment]
Кроме того, можно запустить setup базы данных безопасности, чтобы создать ключи. Сетап удаляет эти три коллекции и создает их заново. Для запуска сетапа, нужно взять вот этот файл: https://github.com/tshemsedinov/impress/blob/master/examples/exampleApplication/applications/example/setup/setup.renameToJs переименовать его в .js и перезапустить Impress, в консоли смотреть вывод. Постом перезапустить Impress опять и setup уже будет помечен, как исполненный, второй раз не запустится.
