### ISSUE TITLE
Не получается установить cookie

### ISSUE THREAD

**Issue by ReasonX7** [tshemsedinov/impress#293]
Сервер Impress присылает такой cookie: `SID=vDAqgF4KMKFvZmc1t6NevC7WgLe1cKssufK2OdwwSKKdK9ptkBDS2TNKeMYp472e; expires=Sun, 31 Jan 2100 22:00:00 GMT; Path=/; Domain=localhost; HttpOnly`
В `document.cookie` он писаться не хочет. Удается записать только, если сократить его до:
`SID=vDAqgF4KMKFvZmc1t6NevC7WgLe1cKssufK2OdwwSKKdK9ptkBDS2TNKeMYp472e`
Google, к сожалению, ответа не нашел.

**Comment by ReasonX7** [comment]
Проблема в `localhost`. Вместо него нужно юзать `127.0.0.1`.
PS: `document.cookie = SID=vDAqgF4KMKFvZmc1t6NevC7WgLe1cKssufK2OdwwSKKdK9ptkBDS2TNKeMYp472e; expires=Sun, 31 Jan 2100 22:00:00 GMT; Path=/; Domain=localhost; HttpOnly` - полная ерунда.

**Comment by tshemsedinov** [comment]
Проблема с ```localhost``` хорошо известна, но ты непонятно выражаешься. Я бы не догадался что речь идет об этой проблеме. Но еще флаг, HttpOnly - с ним ты не считаешь куку локально. А зачем вообще ее считывать не нужно?

**Comment by ReasonX7** [comment]
Раньше с куками не работал, поэтому сделал такую ересь, как присваивание куки HttpOnly в document.cookie.

**Comment by ReasonX7** [comment]
А как работать с `*.everyone.template`? У меня есть два файла `auth.template` и `auth.everyone.template`. Вне зависимости от того залогинился я или нет, всегда отображает `everyone`.

**Comment by tshemsedinov** [comment]
```auth.template``` должен отдаваться тому, кто вообще не имеет сессии, а ```auth.everyone.template``` соединению с сессией, но у которой не установлена группа или если группа есть, но у группы нет своего шаблона. И уже ```auth.groupname.template``` если есть сессия и имя группы ```groupname```.

**Comment by tshemsedinov** [comment]
Получилось?

**Comment by ReasonX7** [comment]
Да. Без понятия, что я сделал, но работает отлично.
