### ISSUE TITLE
Изменение группы пользователя

### ISSUE THREAD

**Issue by ReasonX7** [tshemsedinov/impress#295]
Если во время работы сервера поменять группу пользователя, скажем с users на admins и залогинится, то не взирая на то что `client.user.group == "admins"` и `client.session.group == "admins"`, шаблоны `*.admins.template` и всё, у чего в `access` прописано `groups = ["admins"]`, доступным станет, только после перезапуска сервера. Почему так происходит?

**Comment by tshemsedinov** [comment]
Потому, что группа берется из кеша в application.sessions и application.users, можно при изменении группы не перезапускать сервер, а изменять данные в кеше, удалить данные из кеш, чтобы они перечитались или же перелогинить пользователя.

**Comment by ReasonX7** [comment]
```
application.sessions[client.sid].group = group;
application.users[client.session.login].group = group;
```
Работает. Спасибо!

**Comment by tshemsedinov** [comment]
Можно даже проще
```JavaScript
client.user.group = group;
client.session.group = group;
```
Как-бы хорошо наверно сделать чтобы это в одном месте менялось и вообще, чтобы была функция ```impress.security.setUserGroup``` и она и в память писала бы и базу (да еще если база подключена и через абстрактный интерфейс в разные базы). Нужно потом допилить удобства.
