### ISSUE TITLE
Implement block-list based on IP and SID

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#301]

**Comment by tshemsedinov** [comment]
```client.block(msec);``` block IP and SID for milliseconds or infinite if 0 or not specified
```client.blockIP(msec);``` block by IP
```client.blockSID(msec);``` block by SID

**Comment by itadapter** [comment]
I'd suggest you look at the Gate we did in NFX. 
Similar concept only we have not created any fixed methods.
Instead you can set named variables and GATE passes all requests via the rule engine.

That way you can filter not only on SID-based logic but i.e. if someone tries to upload too much, or buy too many thins at once

**Comment by tshemsedinov** [comment]
Спасибо, посмотрю как в NFX сделано, по ограничению нагрузки вообще мало где есть хорошие решения, все что видел очень примитивное, на бизнес-логику приложений вообще не ориентированное, а тут да, согласен, нужно иметь возможность ограничивать любой параметр.

**Comment by itadapter** [comment]
Here are some unit tests. We also have "groups"
https://github.com/aumcode/nfx/blob/master/Source/Testing/NUnit/NFX.NUnit/IO/NetworkGate/NetGateTests.cs
