### ISSUE TITLE
Add deny/allow by IP to access.js

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#306]
deny: [ array of string IPs ] or 'all'
allow: [ array of string IPs ] or 'all'

**Comment by itadapter** [comment]
Are  partial IPs, like "22.33.4*" supported?

**Comment by tshemsedinov** [comment]
Нужно конечно

**Comment by itadapter** [comment]
Another good denial policy would be variable based.
Deny by expression i,e: "deny:  '$new_session>3'", then you can set the variable from code,
this is used for session flood and stuff. All variables auto-"decay" at the set rate: i.e.
var: { name: "new_session" decay_by: "1" perSecond: "60"}
most servers do not have such facilities, and can allocate new sessions (where permitted) until
 the machine runs out of resources.
Session allocation is one of the "flood" types that attackers can do and can not be easily detected at the hardware level as session ID may be invalid and hardware firewall has no way of knowing that
