### ISSUE TITLE
can't restart impress from node.

### ISSUE THREAD

**Issue by aagafonov** [tshemsedinov/impress#315]
I'm trying to restart impress from custom impress api
here is content of post.js

module.exports = function(client, callback) {
  var sys = require('sys')
  var exec = require('child_process').exec;

  function puts(error, stdout, stderr) { 
    sys.puts(stdout) 
  }

  exec("sh -c 'impress restart'", puts);
}

after submitting post request it killls all processes, raises up master process but fails to raise any child processes

**Comment by tshemsedinov** [comment]
There is no such possibility and it will not be implemented in near future.
