### ISSUE TITLE
Test autostart on different OS

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#316]

**Comment by tshemsedinov** [comment]
@johnbizokk напиши на чем оно сейчас работает и тут же можно время от времени делать заметки, как только потеститшь на других ОС

**Comment by johnbizokk** [comment]
На текущий момент есть скрипты для Ubuntu 15.04, CentOS 7/6.5, FreeBSD 10.1. Для CentOS и Ubuntu уже  допилил и протестил скрипты, сейчас тестирую FreeBSD. 
Планирую полностью закончить скрипты и потестить на всях осях до 16 августа.

**Comment by johnbizokk** [comment]
К сожалению, доделать данную задачу к выше указанному сроку не получилось, из-за загрузки по другим задачам. Постараюсь ускорить работу по данной задаче на сколько это возможно. По ходу решения данной задачи, буду выкладывать скрипты после тестирования.

**Comment by tshemsedinov** [comment]
Вольно, все правильно, здесь как на войне, есть дела на вчера, а прочие дела будем на пенсии доделывать. В случае чего, внезапно доложить обстановку )

**Comment by johnbizokk** [comment]
А скрипты, выкладывать сюда или сразу pull request в impress-cli?
Нужно ли сразу вносить правки в install.sh?

**Comment by johnbizokk** [comment]
Во **FreeBSD** обнаружилось, что **command name** при запуске Impress - "**node**" (видимо берётся название у родительского процесса при запуске (**nohup node server.js**)), при этом в блоке stop, используется команда killall (**'killall "impress srv"**'), которая не распознаёт Impress из-за неправильного command name. Предлагаю использовать kill по pid, либо написать if, для non-linux OS.

**Comment by tshemsedinov** [comment]
1. @johnbizokk делай PR в impress-cli минимальными отдельными законченными частями.
2. Посмотри в коде, где это происходит https://nodejs.org/api/process.html#process_process_title и почитай, чего в ноде это под юниксами не пашет, там что-то про макось написано, это же ветка фри, ноги из одного места растут, можно копать по поводу макоса.
