### ISSUE TITLE
Вопрос про `applications\myApp\client`

### ISSUE THREAD

**Issue by dimon-durak** [tshemsedinov/impress#340]
Расскажите, пожалуйста, как правильно использовать клиентские тулзы.

Правильно ли я понял, что `myApp\client` для файлов типа `gulpfile.js` и/или `gruntfile.js`? 
Или их нужно класть в корень приложения `applications\myApp`, `myApp\client` это `src` для gulp\grunt, а `dest` это `myApp\static`. 

Правильно ли указывать в `.bowerrc` путь в `myApp\static`? Или bower-компоненты должны быть в  `myApp\client`, а эта директория монтируется к корню сайта так же, как и  `myApp\static`

**Comment by tshemsedinov** [comment]
В ```/client``` кладем исходники фронтенда, все конфиги сборщиков и препроцессоров, их зависимости и скрипты (это ```src```), а в ```/static``` потом все собранное сваливается (т.е. это ```dest```). Папка ```/client``` ниоткуда из внешнего мира не видна, а видны ```/static``` и ```/server```, которые обе являются корнем сайта, с той лишь разницей, что ```/static``` не исполняется на сервере, а ```/server``` исполняется (содержит API, шаблоны, обработчики вебсокетов и SSE). Такое разделение и удобнее и безопаснее. Старый каталог ```/app``` (в котором было все это смешано) упразднен за неинформативное название и потенциальное место уязвимости.

Если что, вопросы теперь можно слать сюда, если это просто вопросы, не касающиеся предложений о внесении изменений и дополнений в Impress: https://toster.ru/tag/impress/questions иначе пишите в Github.

**Comment by dimon-durak** [comment]
Спасибо за ответ и за тостер. 
Кстати, может завести [чатик](https://gitter.im/)?

**Comment by tshemsedinov** [comment]
Не, чатики в принципе бессмысленны, вся информация в них теряется, а оперативности ответов они не добавляют, какая разница, где быстро ответить, на гитхабе и тостере или в чате.
