### ISSUE TITLE
Research what can we use from ES6

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#390]

**Comment by tshemsedinov** [comment]
Это из несрочного, когда выйдет версия node.js слитая с io.js нужно будет определить, что из тех возможностей ES6, (которые будут доступны без специальных ключей) можно использовать для повышения производительности в Impress. Сразу предупреждаю, что промисы нам в ядре ноды не нужны, они лишь обертка вокруг колбеков и ничего не ускорят. Все, что относится к читаемости кода можно применять, но не особо увлекаться, а впервую очередь то, что позволит оптимизировать код, ускорить его или уменьшить использование памяти. Например, если родные классы будут работать быстрее прототипов, то можно сделать классы Client не прототипом, а классом, и Application тоже классом, а не замыканием. Кто возьмется? @tblasv, @aagafonov, @j-martyn, @johnbizokk, @ReasonX7 ?

**Comment by j-martyn** [comment]
Мне интересно, я уже даже немного посмотрел, но пока ничего не нашел что реально быстрее работает, по тем бенчмаркам, которые есть, например [раз](http://www.incaseofstairs.com/2015/06/es6-feature-performance/), [два](http://kpdecker.github.io/six-speed/), разве что Map и Set. Но, конечно, надо будет тестить.
