### ISSUE TITLE
Load custom core modules

### ISSUE THREAD

**Issue by Sensarg22** [tshemsedinov/impress#454]
Возможность загрузки собственных модулей ядра Impress например для impress.security.

**Comment by tshemsedinov** [comment]
Собственные модули ядра нужно писать таким образом:
1. Делаем форк на гитхабе
2. Пишем модуль, например, impress.securuty.pgsql.js
3. Тестируем и/или используем свой вариант
4. Делаем pull request в основную репу impress
5. Я склеиваю, делаю кодревью, оптимизирую, публикую новую версию
6. Становимся котрибьютерами и используем основную репу

**Comment by Sensarg22** [comment]
ок

8 декабря 2015 г., 4:37 пользователь Timur Shemsedinov <
notifications@github.com> написал:
