### ISSUE TITLE
Application backend events

### ISSUE THREAD

**Issue by Sensarg22** [tshemsedinov/impress#458]
Необходимо синхронизировать между воркерами application.users и application.sessions при входе и выходе пользователей. Стратегия сервера cluster. В методе `application.security.signIn` публикую событие:
```javascript
if (application.isWorker) {
   application.backend.emit('signIn', { user: user, session: client.session});
}
```
в директории init приложения я разместил обработчик слушающий данное событие:
```javascript
application.backend.on('signIn', function (data) {
    var user = data.user;
    var session = data.session;
    if (user.login && !application.users[user.login]) {
        application.users[user.login] = user;
    }
    if (session.sid && !application.sessions[session.sid]) {
        application.sessions[session.sid] = session;
    }
    console.log(application.nodeId+ ': signIn: ' + user.login + ' sid: '+ session.sid);
});
```
На сколько я понял данное событие должно доставляться в каждый воркер посредством  транспорта настроенного в файле конфигурации сервера `scale.js`, но этого не происходит событие доставляется только в тот же воркер в котором и было опубликовано. Что я делаю не так?

**Comment by tshemsedinov** [comment]
Это очень большой вопрос, который я разделю на X ответов:

1. Синхронизировать ```application.users``` и ```application.sessions``` между воркерами не нужно, вместо этого нужно использовать или прилипание сессий к процессу по IP ```/config/scale.js/strategy = 'sticky'``` при помощи встроенного балансировщика или же использовать внешний балансировщик (софтварный nginx или аналог или хардварный) и запускать импресс в режиме ```/config/scale.js/strategy = 'bundle'``` или же для того же режима ```bundle``` можно использовать балансировку на стороне клиента, где и прилипать к процессу (потому, как у каждого процесс свой порт в этом режиме). Но самое простое, это конечно же серверная балансировка в режиме ```sticky```, но она может глючить на windows и везде будет убивать производительность.

2. Если хочется синхронизировать данные между воркерами, то это можно делать даже без событий, автоматически, помещая их в определенное место: ```application.state.data```
Вот тут есть пример: https://github.com/tshemsedinov/impress/blob/master/applications/example/init/state.renameToJs
Синхронизация есть полная или инкрементальная (поддерживающая конкурентные изменения в разных процессах, но только для цифр). Конечно, для синхронизации есть определенное время, пока изменения распространятся, это нужно иметь в виду, кроме того, есть таймаут синхронизации, т.е. несколько изменений склеиваются. Мастер процесс не синхнонизируется. Синхронизация работает и между несколькими серверами, не только между воркерами.

3. Можно синхронизировать и вручную, подвешиваясь на события ```application.backend.on``` и ```application.backend.emit```. Но тут действительно была ошибка, я ее исправил, можете пробовать. Пример тут: https://github.com/tshemsedinov/impress/blob/master/applications/example/init/event.renameToJs

**Comment by Sensarg22** [comment]
Спасибо:)

**Comment by dmitrystas** [comment]
У меня по прежнему (или снова) не работает это. Слушатель срабатывает только в том процессе, откуда был emit. Например, в \ias\applications\example\init\event.js делаю
```
application.backend.on('test', function(data) {
  console.log('Event "test" received by: ' + application.nodeId);
  console.log('  data: ' + api.json.stringify(data));
});

if (application.nodeId == 'S1N1') {
	api.timers.setInterval(function() {
	  application.backend.emit('test', { sender: application.nodeId, data: 'data' });
	}, 5000);
}
```
при этом в консоли имеем
```
  JSTP listen on 127.0.0.1:250 by Master(30166/S1N0) Cloud Controller
  HTTP listen on 127.0.0.1:38881 by Worker(30179/S1N1)
  HTTP listen on 127.0.0.1:38882 by Worker(30180/S1N2)
Event "test" received by: S1N1
  data: {"sender":"S1N1","data":"data"}
Event "test" received by: S1N1
  data: {"sender":"S1N1","data":"data"}
...
Event "test" received by: S1N1
  data: {"sender":"S1N1","data":"data"}
```
Т.е. только тот же процесс ловит.

А по поводу application.state.data - так вообще
```
 TypeError: Cannot read property 'event' of undefined
  EventEmitter.impress.cloud.state (impress.cloud.js:119:25)
  EventEmitter.<anonymous> (impress.cloud.js:197:34)
  emitOne (events.js:101:20)
  EventEmitter.emit (events.js:188:7)
  Timeout.sendDelta (impress.state.js:42:25)
  tryOnTimeout (timers.js:228:11)
  Timer.listOnTimeout (timers.js:202:5)
```
Исходя из того, что я не увидел по коду, чтобы impress.cloud.socket где то был объявлен, то в принципе и не удивительно. Удивительно другое - как у вас это работает?

**Comment by tshemsedinov** [comment]
В новых версиях мы все разобрали и переписываем, синхронизация сломалась, я знаю
