### ISSUE TITLE
WS and SSE events not working

### ISSUE THREAD

**Issue by SkeLLLa** [tshemsedinov/impress#459]
Hi, @tshemsedinov.

I've tried to run an example application. Before I've followed steps from readme, renamed example app folder to "myapp" and made default config.

Ajax and other get/post requests are working correctly. But when I tried WS example, I've received an error:
```
TypeError: Cannot read property 'accept' of undefined
  module.exports (/myqpp/server/examples/events/connect.ws/get.js:2:36)
```
I've tried to fix this and modified line with error by following:
```
var connection = client.req.connection.websocket.request.accept();
```

But it not helped a lot, because I've got a new error:
```
HTTP 510	Not Extended	/examples/events/connect.ws
```
The same 510 error code I also get when I try to connect via SSE.

May be I've missed something? Do you have any idea what it can be?

My config - latest impress and:
```
 Impress AS:
    Node.js: 5.0.0
         v8: 4.6.85.28
      libuv: 1.7.5
       zlib: 1.2.8
   Open SSL: 1.0.2d
HTTP parser: 2.6.0
         OS: Linux 4.1.6-ck x64
```

Thanks.

**Comment by SkeLLLa** [comment]
I've made some debug and find out that if application has no database configured function at https://github.com/tshemsedinov/impress/blob/master/lib/impress.js#L222 will never call a callback. So plugin mixin will also never run and plugins such as WS or SSE will not work.

@tshemsedinov , I know that application without any DB is quite uncommon, but I think it would be useful to allow users to configure an application without any DB (for tests, mockups and other things). 

From my point of view there are two options here: call `openApplicationDatabases` function callback in any case, even if there is no DB in application and provide error or other helpful info in callback as argument. Or make a better check for `application.config.databases`, because in case when there are no databases it just an empty object, but it coerced to `true` in if statement.

**Comment by tshemsedinov** [comment]
Sorry for a long delay but I can't reproduce your case and can't test your solution because everything works well without it at my laptop, but maybe you have different environment. I have ubuntu 14 here and tomorrow will test on windows 7 and 10, centos 6 and 7.

**Comment by SkeLLLa** [comment]
@tshemsedinov, what dou you have in `databases.js` file? To reproduce this it should be empty or contain just 
```
module.exports = {};
```

If it will be empty the condition in https://github.com/tshemsedinov/impress/blob/master/lib/impress.js#L222 will be false and we never call `api.db.openApplicationDatabases` and never reach the callback in it, that call `impress.mixinPlugins`

If the databases file will contain `module.exports = {}` then we pass that condition, but in https://github.com/tshemsedinov/impress/blob/master/lib/db.js#L56 it never call a callback function in case when there are no keys in object.

Also there is double check here for the same params: https://github.com/tshemsedinov/impress/blob/master/lib/db.js#L54
https://github.com/tshemsedinov/impress/blob/master/lib/impress.js#L222

**Comment by tshemsedinov** [comment]
Yes, you are right @SkeLLLa

**Comment by SkeLLLa** [comment]
@tshemsedinov, thanks.
