### ISSUE TITLE
Do not serve gz for compressed files

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#467]
Issue #465 added ```.gz``` files support for cache.
But it searches for  ```.gz``` files even if files are already compressed (i.e. gif files can't have something like ```/images/logo.gif.gz```)

**Comment by SkeLLLa** [comment]
@tshemsedinov, I suppose that searching for `.gz` could be disabled at all for all files that have extension from this array https://github.com/tshemsedinov/impress/blob/master/lib/impress.constants.js#L69.

**Comment by tshemsedinov** [comment]
@SkeLLLa yes , as it used here https://github.com/tshemsedinov/impress/blob/master/lib/impress.application.js#L632
