### ISSUE TITLE
Initialization impress.security before initializing application.databases

### ISSUE THREAD

**Issue by stokaboka** [tshemsedinov/impress#484]
Initialization impress.security before initializing application.databases:
as result  - Security provider can`t be loaded

application load sequence:
> Impress Application Server starting, reading configuration
>   HTTP listen on 192.168.10.30:80
>   RPC listen on 127.0.0.1:250
> Mixin security dabase provider: application.databases=undefined  _impress.security initialization (master)_
> Debugger listening on port 60806
> db.openApplicationDatabases _application.databases initialization_
> db.openDatabase impress
> db.openDatabase: 1 application.databases=undefined
> db.openDatabase: 2 application.databases=[object Object]
> db.openDatabase: driver for mongodb = [object Object]
> db.mongodb.open database.url=mongodb://192.168.0.11:27017/impress
> db.mongodb.open err=null
> Mixin security dabase provider: application.databases=undefined _impress.security initialization (worker)_
> db.openApplicationDatabases _application.databases initialization_
> db.openDatabase impress
> db.openDatabase: 1 application.databases=undefined
> db.openDatabase: 2 application.databases=[object Object]
> db.openDatabase: driver for mongodb = [object Object]
> db.mongodb.open database.url=mongodb://192.168.0.11:27017/impress
> db.mongodb.open err=null

hastily made hack (impress.js):
```
impress.loadApplication = function(appName, dir, callback) {
  var application = new api.events.EventEmitter();
  application.name = appName;
  application.dir = dir;
  impress.mixinPlugins(application);
  impress.applications[application.name] = application;
  application.createSandbox(function() {
    application.loadConfig(function() {
      application.preprocessConfig();
      application.log.init();
      application.log.open(function() {
        application.emit('start');
        api.db.openApplicationDatabases(application, function() {
          application.loadPlaces(function() {
            application.emit('started');
            // application.cache.preload('/');
            /* TODO  init impress.security after DBs init  */
            console.log("IMPRESS: application.databases="+application.databases);
            console.log("IMPRESS: application.databases.security="+application.databases.security);
            if (application.databases && application.databases.security) {
              var provider = impress.security.getDatabaseProvider(application.databases.security.schema);
              if (provider) provider.mixin(application);
            }
            // END  init impress.security after DBs init
            callback();
          });
        });
      });
    });
  });
};

```
it works), but it does not solve the problem. it's just an illustration

**Comment by aqrln** [comment]
Now `api.db.openApplicationDatabases` emits an event when databases are loaded and the security plugin has a handler for this event. It is the simplest solution.

**Comment by stokaboka** [comment]
Thanks, security works fine )

**Comment by stokaboka** [comment]
Thanks, security works fine
