### ISSUE TITLE
How to create custom impress plugins (modules)?

### ISSUE THREAD

**Issue by SkeLLLa** [tshemsedinov/impress#9]
I've installed example and it has only `sites` folder and `config.js`, `server.js`, `setup.js`. Now I need to create custom module (plugin) or override existing. I've tried one way: cloned impress from git, added test plugin into it and then configured my project to use impress from local git, not from npm. And this way worked. Is this right way to add custom modules to impress or may-be there is another way to do it?

**Comment by tshemsedinov** [comment]
This functionality is fully absorbed by special "places", e.g.
1. Place applied libraries here /appName/lib/*.js
2. Place application initialization code here /appName/init/*.js
3. Place application setup code (run once) here /appName/setup/*.js
4. Place models here /appName/model/*.js
5. Place scheduled tasks here /appName/tasks/*.js
Plugins most likely should be placed in /lib or /init
